In [44]:
import numpy as np
import pandas as pd

In [45]:
df = pd.read_csv('XSS_dataset.csv')
df

Unnamed: 0                                           Sentence  Label
0               0  <li><a href="/wiki/File:Socrates.png" class="i...      0
1               1               <tt onmouseover="alert(1)">test</tt>      1
2               2  \t </span> <span class="reference-text">Steeri...      0
3               3  \t </span> <span class="reference-text"><cite ...      0
4               4  \t </span>. <a href="/wiki/Digital_object_iden...      0
...           ...                                                ...    ...
13681       13681             <img onpointerenter=alert(1)>XSS</img>      1
13682       13682  <source onbeforepaste="alert(1)" contenteditab...      1
13683       13683  <div draggable="true" contenteditable>drag me<...      1
13684       13684  <li><cite id="CITEREFDomingos2015" class="cita...      0
13685       13685                                         \t </span>      0

[13686 rows x 3 columns]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13686 entries, 0 to 13685
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  13686 non-null  int64 
 1   Sentence    13686 non-null  object
 2   Label       13686 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 320.9+ KB


In [47]:
df.drop(df.columns[df.columns.str.contains(
    'unnamed', case=False)], axis=1, inplace=True)

In [48]:
df.head(15)

Sentence  Label
0   <li><a href="/wiki/File:Socrates.png" class="i...      0
1                <tt onmouseover="alert(1)">test</tt>      1
2   \t </span> <span class="reference-text">Steeri...      0
3   \t </span> <span class="reference-text"><cite ...      0
4   \t </span>. <a href="/wiki/Digital_object_iden...      0
5   <li id="cite_note-118"><span class="mw-cite-ba...      0
6   <li><a href="/wiki/Contextualism" title="Conte...      0
7   <li id="cite_note-Representing_causation-95"><...      0
8    <tr><td class="plainlist" style="padding:0 0....      0
9                                          \t </span>      0
10  <li><a href="/wiki/Mind%E2%80%93body_problem" ...      0
11  <a onblur=alert(1) tabindex=1 id=x></a><input ...      1
12  <col draggable="true" ondragenter="alert(1)">t...      1
13      <caption onpointerdown=alert(1)>XSS</caption>      1
14                                         \t </span>      0

In [49]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re
ps = PorterStemmer()
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [50]:
corpus = []
for i in range(len(df)):
  review = re.sub('[^a-zA-Z]',' ', df['Sentence'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if word not in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)
corpus[0]

'li href wiki file socrat png class imag img alt socrat png src upload wikimedia org wikipedia common thumb c cd socrat png px socrat png decod async width height class noview srcset upload wikimedia org wikipedia common thumb c cd socrat png px socrat png x upload wikimedia org wikipedia common thumb c cd socrat png px socrat png x data file width data file height href wiki portal philosophi titl portal philosophi philosophi portal li ul'

In [51]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
X_arr = X.toarray()
X_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [52]:
# visualizing as a dataframe
df_1 = pd.DataFrame(data = X_arr, columns = vectorizer.get_feature_names_out())
df_1

aa  aaa  aaaa  aaaaa  aaaaaa  aaaaaaa  aaaaaaaa  aaaaaaaaa  aaaaaaaaaa  \
0       0    0     0      0       0        0         0          0           0   
1       0    0     0      0       0        0         0          0           0   
2       0    0     0      0       0        0         0          0           0   
3       0    0     0      0       0        0         0          0           0   
4       0    0     0      0       0        0         0          0           0   
...    ..  ...   ...    ...     ...      ...       ...        ...         ...   
13681   0    0     0      0       0        0         0          0           0   
13682   0    0     0      0       0        0         0          0           0   
13683   0    0     0      0       0        0         0          0           0   
13684   0    0     0      0       0        0         0          0           0   
13685   0    0     0      0       0        0         0          0           0   

       aaai  ...  znpg  zombi  zonhsaw  zr  zu  zuckerberg  zxjusvaviitkb  \
0         0  ...     0      0        0   0   0           0              0   
1         0  ...     0      0        0   0   0           0              0   
2         0  ...     0      0        0   0   0           0              0   
3         0  ...     0      0        0   0   0           0              0   
4         0  ...     0      0        0   0   0           0              0   
...     ...  ...   ...    ...      ...  ..  ..         ...            ...   
13681     0  ...     0      0        0   0   0           0              0   
13682     0  ...     0      0        0   0   0           0              0   
13683     0  ...     0      0        0   0   0           0              0   
13684     0  ...     0      0        0   0   0           0              0   
13685     0  ...     0      0        0   0   0           0              0   

       zxjzaw  zyb  zzd  
0           0    0    0  
1           0    0    0  
2           0    0    0  
3           0    0    0  
4           0    0    0  
...       ...  ...  ...  
13681       0    0    0  
13682       0    0    0  
13683       0    0    0  
13684       0    0    0  
13685       0    0    0  

[13686 rows x 5566 columns]

In [53]:
y = pd.get_dummies(df['Label'])
y = y.iloc[:, 1].values

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_arr, y, test_size = 0.2, random_state = 7)

In [55]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model = model.fit(X_train, y_train)
pred = model.predict(X_test)
pred

array([0, 0, 0, ..., 0, 1, 0], dtype=uint8)

In [56]:
from sklearn.metrics import confusion_matrix
cf = confusion_matrix(y_test, pred)
cf

array([[1146,  100],
       [   2, 1490]])

In [57]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, pred)
accuracy

0.9627465303140978